### ISSUE TITLE
Error with HourlyCounter after 99h59min59s

### ISSUE THREAD

**Issue by xibman** [objectivehtml/FlipClock#162]
Hi all, 
i discover a small problem with the last version of the lib, after 99h59min59s the lib add a new digit on minute, not on hour 

The example of the bug: http://jsfiddle.net/a7hofx8L/

**Comment by objectivehtml** [comment]
Just FYI, I have this fixed in the next build. I just refactored the entire library, rewriting many components to be more simple with better, less leaky abstractions. Check out the dev branch once I get it updated for details. We are working towards an overall refresh and update to the library as outlined here: https://github.com/objectivehtml/FlipClock/issues/161
