### ISSUE TITLE
Countdown and Angular

### ISSUE THREAD

**Issue by guidoajansen** [objectivehtml/FlipClock#165]
I made a FlipClock angular directive and I'm having trouble getting the counter to actually animate as a countdown. Now I have to admit this is all kinda new to me so I wouldn't be surprised if I completely overlooked something or just did something very silly.

Unless I understood this incorrectly setCountdown should change the direction of the flip animation, however both when I set it manually to true or when I use decrement() (which sets it to true as well) the animation is still one of the increment. I want the number to change immediately to the updated data. Any way to fix this or is this because of Angular?

.directive('flipclock', function(){
  return {
    restrict: 'EA',
    scope: {
      data: '=',
    },
    link: function(scope, element, attrs){
      var counter = $(element).FlipClock(scope.data, {
        clockFace: 'Counter',
        minimumDigits: '3'
      });

      scope.$watch('data', function(newVals, oldVals) {
        var change = newVals - oldVals;
        if (change > 0) {
          counter.setCountdown(false);
          counter.setTime(scope.data);
        }
        if (change < 0) {
          counter.setCountdown(true);
          counter.setTime(scope.data);
        }
      }, true);
    }
  }
});

**Comment by objectivehtml** [comment]
I agree. I am not sure that flipping upwards should be built into the default theme. Going by the desgn logic of skewmorphism, gravity is controlling the clock. In the real world, I have only seen these clocks flip top to bottom. The clock can countdown instead of up, but the animation is unchanged.

If this is really a desired functionality, it probably belongs as a new theme in a future v1.x release.
