### ISSUE TITLE
Add a Universal Module Definition

### ISSUE THREAD

**Issue by sbaechler** [objectivehtml/FlipClock#171]
Javascript module loaders like Browserify and Webpack are becoming increasingly popular.
It is possible to use FilpClock with a script loader by injecting jQuery for the module import, but it is currently not possible to mock the library and do any unit tests in a DOM-less test suite such as Jasmine if the code under test is using FilpClock.

Ecmascript 6 will be using the CommonJS syntax, so a UMD does make sense. While AMD (require.js) is currently more popular in the browser, this will most likely change in the future.

There is a simple wrapper for jQuery plugins together with a build task here:
https://github.com/umdjs/umd

**Comment by objectivehtml** [comment]
I have been working on some major changes that will help with testing each individual component. Most of the components had leaky abstractions and everything was coupled with the DOM. This has been fixed in the dev branch, but I have not incorporated the UMD (or AMD) module stuff yet.

Is it possible for you to give some sort of brief code example for how this would be implemented with FlipClock. FlipClock isn't really a jQuery plugin, but rather has a jQuery wrapper for convenience. Right now, the only thing that requires jQuery is the DOM selector, which I intend to decouple in the future. (Already been decoupling from jQuery for a while now).

I personally don't have a ton of experience writing AMD modules. I am happy to include these changes, just not 100% sure where to start or how to go about it without breaking the library.

**Comment by sbaechler** [comment]
Unfortunately I don't have any experience writing UMD libraries. Since you are already using closures I think it's just a small step to go UMD. Instead of defining a global variable FlipClock, use the UMD wrapper and 'require' jQuery.

I started using [Webpack](https://github.com/webpack/webpack) for my latest project and really liked it. It's like Browserify but better. You can be global variable free and don't have to worry about the load order of your Javascripts anymore.

**Comment by fkm** [comment]
Hi there :-)

I recommend the following wrapper. It's not strict CommonJS but will suffice for most use-cases.

```Javascript
;void function (root, factory) {
	if (typeof define === 'function' && define.amd) {
		define(['jquery'], factory);
	} else if (typeof module === 'object' && module.exports) {
		module.exports = factory(require('jquery'));
	} else {
		window.XXX = factory(root.jQuery);
	}
}(this, function ($) {

	return something;
});
````

But as I need the wrapped code as soon as possible, I'll create a fork of the dev-branch and get back to you.

**Comment by fkm** [comment]
Ok. There are circular dependencies. Not quite as easy as I thought to wrap everything.

You can find my progress at:
https://github.com/fkm/FlipClock/tree/dev-1.0.0/src/flipclock/js

But I don't have time to resolve this issue. I'll just have to try to use the bundle as it is now and continue this wrapping project another time.

**Comment by stonys** [comment]
Hi, I'm facing the same issue on how load load FlipClock using webpack. No luck so far.

**Comment by dr0bz** [comment]
I right now faced with the same problem. The webpack plugin script-loader helps: https://github.com/webpack-contrib/script-loader. It's still in globalnamespace, but it's working:)

**Comment by objectivehtml** [comment]
Long time coming on this issue, but the library has been rewritten for es6 syntax. The new v1 release draft is in the js-es6 branch. It fixes this issue. It also uses Rollup for the UMD build, and works with webpack and all the latest es6 stuff.
