### ISSUE TITLE
Starting countdowns on several divs

### ISSUE THREAD

**Issue by jsgv** [objectivehtml/FlipClock#181]
Would like to be able to start the countdown on several divs with just one statement:

``` html

<div class="clocks"></div>
<div class="clocks"></div>
<div class="clocks"></div>

<script>
  $('.clocks').FlipClock(60, {
    clockFace: 'DailyCounter',
    countdown: true
  });
</script>
```

As of now I have to do:

``` html
<div class="clocks one"></div>
<div class="clocks two"></div>
<div class="clocks three"></div>

<script>
  $('.clocks.one').FlipClock(60, {
    clockFace: 'DailyCounter',
    countdown: true
  });
  $('.clocks.two').FlipClock(60, {
    clockFace: 'DailyCounter',
    countdown: true
  });
  $('.clocks.three').FlipClock(60, {
    clockFace: 'DailyCounter',
    countdown: true
  });
</script>
```

**Comment by objectivehtml** [comment]
On a technical level, this could be entirely possible. The issue right now is that the jQuery wrapper returns a `FlipClock.Factory` object, not a jQuery object. If this change was made in the dev branch, all the examples would pretty much break. The dev branch *is*a breaking change anyway, so updating examples and breaking the code really wouldn't be a big issue since this is a breaking change anyway.

So the proposed change would be to change this code:

	$.fn.FlipClock = function(digit, options) {	
		return new FlipClock($(this), digit, options);
	};

To this code:

	$.fn.FlipClock = function(digit, options) {	
		return this.each(function() {
			new FlipClock($(this), digit, options);
		});
	};

**Comment by objectivehtml** [comment]
Closing this thread. If anyone still has this issue on the newest version of the library, open a new issues.
