### ISSUE TITLE
days with more 2 digits

### ISSUE THREAD

**Issue by Ardinis** [objectivehtml/FlipClock#204]
Hello,
There is a problem with displaying the clock when the days number is bigger than 99
Example: http://puu.sh/hNtlH/c5656cb3a4.png with clock.setTime(1444859893);

**Comment by notsoluckycharm** [comment]
Can confirm. Working on my own fix.

![screen shot 2015-05-20 at 5 24 55 pm](https://cloud.githubusercontent.com/assets/609341/7736899/2212f864-ff15-11e4-9f89-15cc0cf0ae46.png)

**Comment by Nelidon** [comment]
can you make a pull request of your commit please ?

**Comment by techieshark** [comment]
@notsoluckycharm did you have a fix for this?

**Comment by techieshark** [comment]
Update: this actually does seem to work. See the `examples/countdown-from-new-years.html`.

**Comment by anwilli5** [comment]
It looks like this issue occurs if you do the following:
```javascript
clock = $('.clock').FlipClock({
    'autoStart': false,
    'clockFace': 'DailyCounter',
    'countdown': true,
});
clock.setTime(diff);
clock.start();
```
as opposed to what is done below (which is also done in the countdown-from-new-years example):
```javascript
clock = $('.clock').FlipClock(diff, {
    'autoStart': true,
    'clockFace': 'DailyCounter',
    'countdown': true,
});
```

A quick fix is to just convert your code to the latter format.

My guess is that it is setting up the digits when it creates the Clock object (two for each field,) and upon starting, the library sees that another digit is needed and just adds it to the end.  Maybe in addition to adding a digit, the code could re-calculate the placement of all the dividers.  I think this would also handle the case where the time is 99:99:99 counting up - I'm guessing that now this will result in 99:99:100 instead of 100:99:99.

**Comment by objectivehtml** [comment]
This has all been addressed in the new js-es6 branch with is the new v1 draft.
