### ISSUE TITLE
Clock not in sync with system time

### ISSUE THREAD

**Issue by kaimys** [objectivehtml/FlipClock#23]
I think the clock is lagging of 2 or 3 seconds in countdown mode. 2 or 3 seconds depending where you start to count: 2 when the new digit starts falling or 3 when it arrived at the bottom.

``` javascript
clock = $('#clock').FlipClock({
  autoStart: false,
  countdown: true,
  callbacks: {
    interval: function() {
      var r = (start.getTime() - (new Date()).getTime()) / 1000;
      console.log([Math.floor(r/3600), Math.floor(r % 3600 / 60), Math.floor(r % 60)]);
    }
  }
});
clock.setTime(next/1000 - 3);
clock.start();
```

**Comment by sskrla** [comment]
Why is this closed? I was about to open a similar issue as it is very much a problem for my application.

If the computer / browser is suspended the timer will be effectively paused. If you switch tabs, intervals are apparently slowed or at least scheduled with extremely low priorities. Which causes considerable drift over even a few minutes.

I am still looking at the code, but I suspect this is because `Face` depends on the interval being called exactly every second and `setInterval` makes no assurances of this. I will most likely be writing a custom face that adjust the counters according to the delta between timer start and now.

**Comment by KyleMcNutt** [comment]
@sskrla You can see issue #155 for a discussion (and a possible workaround) for what your experiencing.
