### ISSUE TITLE
Very difficult to re-size

### ISSUE THREAD

**Issue by dougalx** [objectivehtml/FlipClock#295]
Someone locked the previous issue asking for a responsive solution, and seems to have abandoned this endevour, saying "It's coming in 1.0." Until then, this js is only good for enormous countdown clocks that take up most of the page. It's pretty much impossible to scale it in a way that is smooth, reliable, and predictable across major browsers.

If you're trying to scale flipclockjs in late 2016, you're better off spending your time on some other solution.

**Comment by objectivehtml** [comment]
We have a new dev branch that is scalable. Last year or so has been a struggle to keep with open source endeavors due to work and personal/life issues in addition to moving across the country. I've been working on stuff quietly in my free time where I, and going to have a lot more time devoted to open source projects in the coming months. Sorry to everyone for what looks like an abandoned projects, just had other priorities.

FlipClock 1.0 is very close to being up to date, albeit way behind schedule. All the latest JS techniques will be included in the released. Total UMD support for Browserify, Webpack, Requirejs, etc. The clock faces will theme-able, scalable, etc.

**Comment by dougalx** [comment]
Thank you
