### ISSUE TITLE
Timer does not run on Background in iPhone 

### ISSUE THREAD

**Issue by LavanyaSugumaar09** [objectivehtml/FlipClock#361]
I have used Flipclock.js. Timer must run on background i.e When iPhone is screen locked the timer must continue its counting, please let me know the solution to run Timer even when the iPhone screen is locked.

**Comment by marvinIsSacul** [comment]
The problem is probably that of the Device/Browser. I don't think Flipclock.js is responsible here. Just saying...

**Comment by objectivehtml** [comment]
Just going through some old issues. FlipClock was the cluprit here. It used intervals, and it should have used requestAnimationFrame. I have been working a re-release of FlipClock. Check out the js-es6 branch for more details. The library has been completely rewritten, and this issue was addressed. Flip animation is controlled by GPL now, and should run in the background, or at least update the UI to the correct state once the app is resumed in memory.

**Comment by marvinIsSacul** [comment]
requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life.

[https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame](url)

**Comment by marvinIsSacul** [comment]
So the problem will most likely persist even with the use of requestAnimationFrame() huh

**Comment by objectivehtml** [comment]
I can take a look into this more specifically to make sure its working properly. I do think the requestAnimationFrame is better. I have noticed this behavior is more related to the OS and browser than it is JS. In my tests, I could briefly put the window in the background and it would still run. However, I noticed it would pause if I went to my text editor a for a bit and when the focus was back on the browser it would resume. So the clock doesn't need to be running in the background, but rather, it just needs to resume at the correct time anytime it's brought back into the foreground. Which is why requestAnimationFrame, I think, is an improvement over intervals. 

Also, using intervals would actually cause an inaccurate count. With the JS processing, UI paint, and various loops, it look a little over 1000ms for each interval of the clock. Mostly this was just a few milliseconds, however sometimes up 1100ms if the GPU/CPU was working hard, which means every tick of the clock was longer than a second and the time on the clock would fall behind. requestAnimationFrame should also improve on this as well.

**Comment by objectivehtml** [comment]
Thinking about this a bit more, I think that if you need something to run in the background, the animation of the clock isn't the place to do it. I would try using an interval or something that doesn't involve updating the UI or running with every tick of the clock.

**Comment by marvinIsSacul** [comment]
Yea I think so too.
