### ISSUE TITLE
how to bind event

### ISSUE THREAD

**Issue by ewwink** [objectivehtml/FlipClock#368]
I'm using Firefox and want to bind to interval but I got error

```
var clock = new FlipClock($('.clock'), 10, {
  clockFace: 'MinuteCounter',
  autoStart: true,
  countdown: true,
});
clock.on('interval', function() {
	console.log('test');
});

// TypeError: clock.on is not a function
```

**Comment by objectivehtml** [comment]
Been a long time since I used the old master branch. There is an old dev-1.0.0 that never made it into the master branch that contains this event code. However, the master and dev-1.0.0 branches have been scrapped, and the library has been rewritten from scratch on the js-es6 branch. I would recommend using that branch. I just pushed a big commit of code comments, jsdocs yesterday. You should be able to solve your issue with the new branch.

**Comment by ewwink** [comment]
I use it from https://www.jsdelivr.com/package/gh/objectivehtml/FlipClock I will try that branch and thanks

**Comment by objectivehtml** [comment]
Closing this thread because its a non issue in the upcoming v1 release, currently the `js-es6` branch.
