### ISSUE TITLE
Simple Counter demo error

### ISSUE THREAD

**Issue by lukasz-strzelczyk** [objectivehtml/FlipClock#369]
Simple counter demo has an error:
Any ideas how to solve this?

```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at prepend (Digitize.js:26)
    at Digitize.js:45
    at Array.map (<anonymous>)
    at Digitize.js:44
    at Array.map (<anonymous>)
    at digitize (Digitize.js:43)
    at FaceValue.set (FaceValue.js:68)
    at new FaceValue (FaceValue.js:26)
    at Function.make (Component.js:214)
    at Counter.createFaceValue (Face.js:279)
```

**Comment by objectivehtml** [comment]
This should be fixed now. I broke the code in a recent update when I added support so that values can be passed as a callback function, and apparently didn't test enough to run into this issue. I refactored a bit of code. simple-counter.html works on my end now. I probably need to go through the other examples now, but I have not done that yet.

**Comment by objectivehtml** [comment]
All the examples are fixed in the `js-es6` branch and are included in the new docs. Closing this thread.

**Comment by haocaiMP** [comment]
Is there a specific solution?
