### ISSUE TITLE
FlipClock breaks when uglified.

### ISSUE THREAD

**Issue by Woolfe** [objectivehtml/FlipClock#375]
The version of FlipClock that is on npm (the js-es6 branch) breaks when uglified.

Because FlipClock reads the names of functions, when run through Uglify it gives this error:

`n cannot be rendered because it has no template` which occurs in `DomComponent.js` because `this.name` is a function name generated by Uglify.

Npm modules should handle common build processes that change variable names, such as Uglify.

For those looking for a fix in the meantime, adding `keep_classnames: true` and `keep_fnames: true` to `uglifyOptions` worked for me.

**Comment by brianespinosa** [comment]
@Woolfe the current branch on npm will eventually be deprecated. There is a new es6 branch coming that is currently working if you want to try that instead. I believe that will solve your issues with your build process as well.

**Comment by objectivehtml** [comment]
Thanks for the report. I haven't time to wrap up the es6 branch yet, but this is a known issue. I ran into this myself. The proper fix for this would be to have a method to define the name explicitly of the classes, instead of using that property. The only reason the class names are used is for the new theming stuff that was added.

**Comment by mtr** [comment]
@brianespinosa I've stumbled upon this bug too, and I am using the `js-es6` branch.  The problem should probably be fixed properly, like @objectivehtml suggests.

**Comment by brianespinosa** [comment]
Thanks for confirming this issue still exists in the new branch @mtr 

We will leave this issue open to track to work to fix this in the `js-es6` branch.

**Comment by bonesoul** [comment]
happening here too.

**Comment by objectivehtml** [comment]
Fix coming shortly. Had to step away from the library again for work, but going to get all this pushed through this week even if it kills me.

**Comment by dolbex** [comment]
Any news @objectivehtml ?

**Comment by objectivehtml** [comment]
I finished the documentation and new website build last week, which included a full rewrite of the website which now generates itself with JS doc. But have been slammed with work all week and haven't had a chance to push it over the hill. This issue is one of the last real bug fix that needs to finished, so I will get to it asap.

**Comment by dolbex** [comment]
Who thought a flip clock would be so much work, eh? :)

**Comment by objectivehtml** [comment]
Ha, right. It gets a lot of traffic and downloads but started to slip because it hasn't been updated in forever. I think this next update will set it up for years and allows everything to be extended and overwritten, including the html and theme. Next step is to get another flip effect. I saw a 3d cube effect that would be cool.

**Comment by dolbex** [comment]
Get back to the fun stuff :) Look forward to seeing the updates. We sort-a rolled our own for now but this is something we get request for from time to time. Love to have a go-to.

**Comment by tiesont** [comment]
Ever considered adding a simple donate button to the readme (hint, hint)? Something like this: https://github.com/patharanordev/donate-in-git

**Comment by objectivehtml** [comment]
@tiesont Yeah definitely. That's probably going to happen in the next release. I've have even considered looking into doing 1 small relevant ad on the site, always tech based. I use to get a lot of volume of unique visitors with high engagement, but trickled down as jQuery lost popularity.

**Comment by objectivehtml** [comment]
This issue should be fixed. No longer use `this.constructor.name`. I haven't tested building it and actually minifying it, so if there are more issues post back in the thread.
