### ISSUE TITLE
Cannot build project. Missing quote in hungarian language file.

### ISSUE THREAD

**Issue by ksmith97** [objectivehtml/FlipClock#376]
The project fails to uglify due to a missing quote in the hungarian language pack.
I added the quote and was going to submit a pr but when I built the file I noticed a larger diff in the compiled files. It looks like the last time the file was compiled it did not include all the language packs.  This was unexpected and I did not want to submit a pr with such large changes unless I knew this was expected.

Preferably a new version would be compiled with all the language packs to simplify submitted prs in the future.

**Comment by objectivehtml** [comment]
Are you using the new js-es6 branch? 

FYI, The new branch includes all the languages by default in the build. I am going to change this though to trim the build down and have version of the library that includes them all, but the default will be an opt-in to other languages and English is the default. 

The new version is meant to use `Import` and `require` and ideally not even use the compiled bundles, and just import what you want to use directly. The bundles will still obviously be available on CDN for those that use that way, but best way to use FlipClock is going to be to import it in your own projects and let it handle the bundling.

**Comment by ksmith97** [comment]
The point I was getting at is your master branch does not build.  When you fix the issue preventing the build the compiled version is different than what is currently committed which raises the question of if the compiled version is even value.  If its not just remove it.

If you no longer recommend that people use master you should just merge your new branch to make an updated master.

**Comment by objectivehtml** [comment]
Master branch hasn't been worked on it in several years. There was another partial rewrite in another branch that never made it to fruition. Then I recently rewrote the entire library from scratch. I have not made the js-es6 branch the master because the documentation hasn't been updated yet, and haven't had time to finish it since I did the rewrite. I hope to have time in the next couple of weeks to finish everything and update the website with the new docs. Appreciate the feedback.
